### ISSUE TITLE
tests: Macos-test using github

### ISSUE THREAD

**Issue by Kreyren** [Kreyren/winetricks#37]
As you can see I gave up on this and ragequited, someone contribute it to save my sanity, thanks

```yaml
# Fucking up everything since iPhone 1!
name: iDiot-tests

# Sanitize if usable
on: [push]

jobs:
  build:
    name: macos-test
    runs-on: macos-latest

    steps:
    # Shellcheck doesn't seem to work on macos since it doesn't support containers? (https://github.com/Kreytricks/kreytricks/runs/302690830)
    #- name: shellcheck
    #uses: ludeeus/action-shellcheck@0.0.1
    run: |
      printf '%s\n' "FIXME: Me poor macbook suck at running shellcheck in this repository, please fix me"
```
